### ISSUE TITLE
Page Content Plugin Options: Labels empty

### ISSUE THREAD

**Issue by m10a** [CPS-IT/persons#3]
Hi,
the labels in the "Page Content Plugin Options" in "Allowed excludefields"-Area of the User Group Access List are empty (see Screnshot).

![page-content-plugin-options-empty](https://user-images.githubusercontent.com/12715596/39800504-4c921d7c-5368-11e8-8b95-ac722b65d496.png)

Thanks, Michael

**Comment by dwenzel** [comment]
Thank you for reporting.
