### ISSUE TITLE
Feature Request: Implementation of Ordering of Selected Persons

### ISSUE THREAD

**Issue by m10a** [CPS-IT/persons#4]
Hi,
rather a feature request:

Ordering of the Persons in the flexform-tab "Constraints" of "Selected Persons" is not implemented so far. In PersonRepository findMultipleByUid() is an ordering but there is no setting for it in the flexform.

Can you implement the ordering from the contstraints how it is represented in $recordList?

A possible solutions for TYPO3 7:
https://www.typo3tiger.de/blog/post/extbase-repository-query-findbyuidlist-sortierung.html

But in TYPO3 8 this don't work:
https://stackoverflow.com/questions/46471525/typo3-8-7-query-sorting-with-flexform-uid%C2%B4s

Thanks, Michael

**Comment by dwenzel** [comment]
@m10a 
Sorry Michael, I didn't receive any notification from this repository. We probably messed something up.
We will try and implement your suggestion in one of the upcoming versions.

cheers Dirk

**Comment by dwenzel** [comment]
@eliashaeussler
